### ISSUE TITLE
What's this? Is it an another Jupiter?

### ISSUE THREAD

**Issue by itsu020402** [CoreXDevelopmentTeam/CoreX#6]
I think that these codes:
[https://github.com/JupiterDevelopmentTeam/Jupiter/blob/58bb9badb7f619d6088a046b55a2bd535d77ce1e/src/main/java/cn/nukkit/Server.java](url) 
line from 559 to 587 and these codes:
[https://github.com/CoreXDevelopmentTeam/CoreX/commit/4f982ba1fff48e52d5cafbc1e8a33d395fe9c439](url) line from 455 to 476 at Server.java are very similar, aren't them?

**Comment by Wesley-Van-Neck** [comment]
@itsu020402  well i know your a nukkit fork and i think you have the same license

**Comment by Wesley-Van-Neck** [comment]
and this is a nukkiit fork

**Comment by itsu020402** [comment]
What do you think about my opinion?

**Comment by Wesley-Van-Neck** [comment]
well your right

**Comment by PikyCZ** [comment]
Yea i copy ShulkerBox and Console Logger .. wauu ... itsu jupiter have same license and everyone can copy code ..

**Comment by itsu020402** [comment]
I'm not angry, so you shouldn't be concerned.
